"""`spendguard run -- <command>` — gate a process WITHOUT touching its interpreter.

WHY THIS IS THE DEFAULT (and `install-hook` is not, since 0.8):
`install-hook` writes `sitecustomize.py`/`usercustomize.py` into a venv so every process is gated. It works, and
for a machine you own it is still the most complete option — but in 2026 that mechanism reads as an attack. On
2026-03-24 `litellm` 1.82.8 shipped a malicious `litellm_init.pth` that executed a credential stealer at every
interpreter start (SSH keys, cloud creds, K8s configs). Startup-hook abuse is now MITRE T1546.018, endpoint tools
ship detections for site-customize file creation, and PEP 648 — which would have blessed a sanctioned version —
was rejected. A cost tool in the same category as the compromised package should not ask strangers to let it write
startup hooks as step one.

So this wrapper does what `ddtrace-run` and `opentelemetry-instrument` do: put a bootstrap directory on the CHILD's
PYTHONPATH and exec the command. Properties that matter:
  • NOTHING is written into site-packages, and nothing persists after the process exits;
  • the effect is scoped to that one command — no other process on the machine changes behavior;
  • `unset PYTHONPATH` / not using the wrapper is the complete uninstall;
  • it chains to a host's OWN sitecustomize instead of shadowing it (same courtesy ddtrace-run pays).
The bootstrap file is generated locally from this module (never downloaded) and `spendguard run --show` prints its
exact contents, so a reviewer can read every byte that will execute.
"""
import os
import sys

_BOOTSTRAP = '''\
# Generated by `spendguard run` — DO NOT EDIT. Scoped to a child process via PYTHONPATH; nothing is installed
# into site-packages and nothing persists once that process exits. Print it with `spendguard run --show`.
import os
import sys

# 1) Chain to the host's OWN sitecustomize (if any) so we never silently replace it. We look for it on the path
#    with THIS directory removed — otherwise we would just find ourselves.
try:
    import importlib.util
    _here = os.path.dirname(os.path.abspath(__file__))
    _rest = [p for p in sys.path if p and os.path.abspath(p) != _here]
    for _p in _rest:
        _cand = os.path.join(_p, "sitecustomize.py")
        if os.path.isfile(_cand):
            _s = importlib.util.spec_from_file_location("_host_sitecustomize", _cand)
            _m = importlib.util.module_from_spec(_s)
            _s.loader.exec_module(_m)
            break
except Exception:
    pass

# 2) Arm the gate. Fail-OPEN by design: a cost tool must never be the reason a job doesn't run.
try:
    import spendguard
    spendguard.install()
except Exception as _e:
    if os.environ.get("SPENDGUARD_DEBUG"):
        sys.stderr.write("[spendguard] bootstrap could not install the gate: %r\\n" % (_e,))
'''


def bootstrap_dir():
    """Directory holding the generated bootstrap `sitecustomize.py` (created/refreshed on demand)."""
    from . import config
    d = config.HOME / "bootstrap"
    d.mkdir(parents=True, exist_ok=True)
    p = d / "sitecustomize.py"
    if not p.exists() or p.read_text() != _BOOTSTRAP:
        p.write_text(_BOOTSTRAP)
    return str(d)


def child_env(env=None):
    """A copy of `env` with the bootstrap dir PREPENDED to PYTHONPATH (so it wins over any other sitecustomize),
    preserving anything already there."""
    e = dict(os.environ if env is None else env)
    d = bootstrap_dir()
    cur = e.get("PYTHONPATH", "")
    e["PYTHONPATH"] = (d + os.pathsep + cur) if cur else d
    e["SPENDGUARD_VIA_RUN"] = "1"        # lets `doctor` explain WHY this interpreter is gated
    return e


def main(argv=None):
    argv = list(argv or [])
    if "--show" in argv:                  # reviewability: print the exact bytes that will execute
        print(f"# {bootstrap_dir()}/sitecustomize.py")
        print(_BOOTSTRAP)
        return 0
    if argv and argv[0] == "--":
        argv = argv[1:]
    if not argv:
        print("usage: spendguard run -- <command> [args...]\n"
              "  e.g. spendguard run -- python train.py\n"
              "       spendguard run -- pytest -q\n"
              "Gates that ONE command: the bootstrap goes on its PYTHONPATH, nothing is written to site-packages\n"
              "and nothing persists. `spendguard run --show` prints the exact bootstrap that will execute.")
        return 2
    env = child_env()
    try:
        os.execvpe(argv[0], argv, env)    # replace this process → exit code, signals and stdio pass through natively
    except FileNotFoundError:
        print(f"spendguard run: command not found: {argv[0]}", file=sys.stderr)
        return 127
    except Exception as e:
        print(f"spendguard run: could not exec {argv[0]}: {e}", file=sys.stderr)
        return 126
